### ISSUE TITLE
com.parse.ParseException: function not found

### ISSUE THREAD

**Issue by VihaanVerma89** [cloudinary/cloudinary_android_parse_sample#2]
When trying to upload an image I get this exception in UploadPhotoActivity's startUpload doInBackground function.

```
 uploadParams = ParseCloud.callFunction(Constants.PARSE_SIGN_CLOUD_FUNCTION, args);

//Exception
com.parse.ParseException: function not found
```

	public static final String PARSE_SIGN_CLOUD_FUNCTION = "sign_cloudinary_upload_request";

**Comment by taragano** [comment]
Hi @VihaanVerma89,

I'm truly sorry for the response. In case this is still relevant please share some more information regarding your environment, specifically what version of Java, cloudinary_java and parse SDK are you using?
Also, it'd be great if you could share the full stack trace.

**Comment by bisfrim** [comment]
I get this error when try to upload an image. I'm using the exact same clone you have here on github

11-29 12:44:22.073 18086-18497/com.cloudinary.photoalbum.PhotoAlbumApplication E/CloudinarySample: Error signing request
                                                                                                   com.parse.ParseException: function not found
                                                                                                       at com.parse.ParseCommand.onPostExecute(ParseCommand.java:404)
                                                                                                       at com.parse.ParseRequest$5.then(ParseRequest.java:342)
                                                                                                       at com.parse.ParseRequest$5.then(ParseRequest.java:339)
                                                                                                       at bolts.Task$10.run(Task.java:486)
                                                                                                       at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:97)
                                                                                                       at bolts.Task.completeAfterTask(Task.java:482)
                                                                                                       at bolts.Task.continueWithTask(Task.java:358)
                                                                                                       at bolts.Task.continueWithTask(Task.java:369)
                                                                                                       at bolts.Task$8.then(Task.java:415)
                                                                                                       at bolts.Task$8.then(Task.java:407)
                                                                                                       at bolts.Task$10.run(Task.java:486)
                                                                                                       at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:97)
                                                                                                       at bolts.Task.completeAfterTask(Task.java:482)
                                                                                                       at bolts.Task.access$200(Task.java:27)
                                                                                                       at bolts.Task$6.then(Task.java:351)
                                                                                                       at bolts.Task$6.then(Task.java:348)
                                                                                                       at bolts.Task.runContinuations(Task.java:515)
                                                                                                       at bolts.Task.access$600(Task.java:27)
                                                                                                       at bolts.Task$TaskCompletionSource.trySetResult(Task.java:570)
                                                                                                       at bolts.Task$TaskCompletionSource.setResult(Task.java:604)
                                                                                                       at bolts.Task$10$1.then(Task.java:498)
                                                                                                       at bolts.Task$10$1.then(Task.java:490)
                                                                                                       at bolts.Task$9.run(Task.java:453)
                                                                                                       at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:97)
                                                                                                       at bolts.Task.completeImmediately(Task.java:449)
                                                                                                       at bolts.Task.access$100(Task.java:27)
                                                                                                       at bolts.Task$5.then(Task.java:316)
                                                                                                       at bolts.Task$5.then(Task.java:313)
                                                                                                       at bolts.Task.runContinuations(Task.java:515)
                                                                                                       at bolts.Task.access$600(Task.java:27)
                                                                                                       at bolts.Task$TaskCompletionSource.trySetResult(Task.java:570)
                                                                                                       at bolts.Task$TaskCompletionSource.setResult(Task.java:604)
                                                                                                       at bolts.Task$10$1.then(Task.java:498)
                                                                                                       at bolts.Task$10$1.then(Task.java:490)
                                                                                                       at bolts.Task$9.run(Task.java:453)
                                                                                                       at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:97)
                                                                                                       at bolts.Task.completeImmediately(Task.java:449)
                                                                                                       at bolts.Task.access$100(Task.java:27)
                                                                                                       at bolts.Task$5.then(Task.java:316)
                                                                                                       at bolts.Task$5.then(Task.java:313)
                                                                                                       at bolts.Task.runContinuations(Task.java:515)
                                                                                                       at bolts.Task.access$600(Task.java:27)
                                                                                                       at bolts.Task$TaskCompletionSource.trySetResult(Task.java:570)
                                                                                                       at bolts.Task$TaskCompletionSource.setResult(Task.java:604)
                                                                                                       at bolts.Task$10$1.then(Task.java:498)
                                                                                                       at bolts.Task$10$1.then(Task.java:490)
                                                                                                       at bolts.Task$9.run(Task.java:453)
                                                                                                       at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:97)
                                                                                                       at bolts.Task.completeImmediately(Task.java:449)
                                                                                                       at bolts.Task.continueWith(Task.java:323)
                                                                                                       at bolts.Task.continueWith(Task.java:334)
                                                                                                       at bolts.Task$10.run(Task.java:490)
                                                                                                       at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:97)
                                                                                                       at bolts.Task.completeAfterTask(Task.java:482)
                                                                                                       at bolts.Task.access$200(Task.java:27)
                                                                                                       at bolts.Task$6.then(Task.java:351)
                                                                                                       at bolts.Task$6.then(Task.java:348)
                                                                                                       at bolts.Task.runContinuations(Task.java:515)
                                                                                                       at bolts.Task.access$600(Task.java:27)
                                                                                                       at bolts.Task$TaskCompletionSource.trySetResult(Task.java:570)
                                                                                                       at bolts.Task$TaskCompletionSource.setResult(Task.java:604)
                                                                                                       at bolts.Task$10$1.then(Task.java:498)
                                                                                                       at bolts.Task$10$1.then(Task.java:490)
                                                                                                       at bolts.Task$9.run(Task.java:453)
                                                                                                       at bolts.BoltsExecutors$ImmediateExecutor.execute(BoltsExecutors.java:97)
                                                                                                       at bolts.Task.completeImmediately(Task.java:449)
                                                                                                       at bolts.Task.continueWith(Task.java:323)
                                                                                                       at bolts.Task.continueWith(Task.java:334)
                                                                                                       at bolts.Task$10.run(Task.java:490)
                                                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                                       at java.lang.Thread.run(Thread.java:818)

**Comment by taragano** [comment]
I'm very sorry for our response delay.
I'd be happy to help if this issue is still relevant, however, note that Parse is shut down since on January 30, 2017 (https://parseplatform.github.io/), therefore, unfortunately, we won't be able to offer support to this library at the moment.

**Comment by bisfrim** [comment]
I've moved my app to another hosted site. I've fixed the above error, but now when i try to upload something i get a prompt saying "needs an authenticated user"? Any advise will help. Thanks

**Comment by taragano** [comment]
Thank you for your reply.
It seems that it's not successfully logging in to your Cloudinary account, see:
https://github.com/cloudinary/cloudinary_parse#usage-example

Please consider moving to not using Parse, as it's not supported anymore. You may want to consider using our [Android library](https://github.com/cloudinary/cloudinary_java/tree/master/cloudinary-android) instead.
